### ISSUE TITLE
为什么安装cocoapods，版本不正确。

### ISSUE THREAD

**Issue by oyh5233** [alibaba/ruby.taobao.org#74]
sudo gem install cocoapods --pre，用rubygems.org的源是1.1.0.rc.2  而用taobao.org的源，是1.1.0.beta.2。我看官网描述，说是15分钟同步一次。怎么没有更新呢。

**Comment by dellheng** [comment]
我使用的 fastlane 也遇到了同样问题

**Comment by zhuayi** [comment]
我也遇到同样问题

**Comment by cliulang** [comment]
你们怎么更新到的1.1.0 beta.2?我连1.1.0都更新不到

**Comment by zhuayi** [comment]
删掉了淘宝源,用原生的就可以安装最新的

From:  cliulang
Reply-To:  "alibaba/ruby.taobao.org"
Date:  2016年10月12日 星期三 上午9:56
To:  "alibaba/ruby.taobao.org"
Cc:  zhuayi, Comment
Subject:  Re: [alibaba/ruby.taobao.org] 为什么安装cocoapods，版本不正确。 (#74)

你们怎么更新到的1.1.0 beta.2?我连1.1.0都更新不到

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/alibaba/ruby.taobao.org","title":"alibaba/ruby.taobao.org","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/alibaba/ruby.taobao.org"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cliulang in #74: 你们怎么更新到的1.1.0 beta.2?我连1.1.0都更新不到"}],"action":{"name":"View Issue","url":"https://github.com/alibaba/ruby.taobao.org/issues/74#issuecomment-253097872"}}}

**Comment by pengbins** [comment]
我直接安装也是 beta2, 还是得换回rubygems

**Comment by pengbins** [comment]
不换不知道, 一换发现有一堆更新

**Comment by iBenjamin** [comment]
看这个消息，这个已经不维护了。https://www.oschina.net/news/71749/taobao-gems-ruby-china
